name: build

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Download repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Maven dependency/resolve
        run: mvn dependency:resolve

      - name: Maven install
        run: mvn install -Dmaven.javadoc.skip=true -B -V -e > maven-install-output.txt

      - name: Print logs
        if: ${{ always() }}
        run: |
          tail -n 500 maven-install-output.txt
          tail -n 500 target/it-tests/gwt-jar-test/build.log

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: maven-install-output.txt
          path: maven-install-output.txt

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: gwt-jar-test-build.log
          path: target/it-tests/gwt-jar-test/build.log

